kind: ConfigMap
apiVersion: v1
metadata:
  name: alertmanager-config
  namespace: monitoring
data:
  alertmanager.yml: |-
    global:
      resolve_timeout: 5m
    
    route:
      group_by: ['alertname']
      group_interval: 30s
      repeat_interval: 30s
      group_wait: 30s
      receiver: 'prometheus-msteams'

    receivers:
    - name: 'prometheus-msteams'
      webhook_configs: 
      - send_resolved: true
        url: 'prom-msteams:2000/alertmanager'