apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_ansible-rg_certain-seasnail-k8s_eastus2
    service.beta.kubernetes.io/azure-pip-name: 1c495593-a513-4451-be3d-1be813f8a0d3
    prometheus.io/scrape: "true"
    prometheus.io/port: "9093"
spec:
  selector: 
    app: alertmanager
  type: LoadBalancer 
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000

# apiVersion: v1
# kind: Service
# metadata:
#   name: alertmanager
#   namespace: monitoring
#   labels:
#     kubernetes.io/cluster-service: "true"
#     addonmanager.kubernetes.io/mode: "Reconcile"
#     kubernetes.io/name: "Alertmanager"
# spec:
#   selector:
#     k8s-app: alertmanager 
#   type: ClusterIP
#   ports:
#     - name: http
#       port: 9093
#       protocol: TCP
#       targetPort: 9093