apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: monitoring
  annotations:
      prometheus.io/scrape: "true"
      prometheus.io/port: "9093"
spec:
  selector: 
    app: alertmanager
  type: NodePort  
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 31000

# apiVersion: v1
# kind: Service
# metadata:
#   name: alertmanager
#   namespace: monitoring
#   labels:
#     kubernetes.io/cluster-service: "true"
#     addonmanager.kubernetes.io/mode: "Reconcile"
#     kubernetes.io/name: "Alertmanager"
# spec:
#   selector:
#     k8s-app: alertmanager 
#   type: ClusterIP
#   ports:
#     - name: http
#       port: 9093
#       protocol: TCP
#       targetPort: 9093