apiVersion: apps/v1
kind: Deployment
metadata:
  name: prom-msteams
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prom-msteams
  template:
    metadata:
      labels:
        app: prom-msteams
    spec:
      containers:
      - name: prom-msteams
        image: quay.io/prometheusmsteams/prometheus-msteams
        ports:
        - containerPort: 2000
        env:
        - name: TEAMS_INCOMING_WEBHOOK_URL
          valueFrom:
            secretKeyRef: # Using secret, but not added to index since it is ignored in de .gitignore file
              name: webhook-secret
              key: url
        - name: TEAMS_REQUEST_URI
          value: alertmanager