apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_ansible-rg_adapted-sponge-k8s_eastus2
    service.beta.kubernetes.io/azure-pip-name: 4139c55e-e7c3-4fcd-b8fd-b2ec7a1aa0d1
spec:
  selector: 
    app: prometheus-server
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 30090