{
 "title": "MyApp",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "App Version",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "myapp_info", "legendFormat": "{{ version }}" }
   ]
  },
  {
   "title": "Connected Devices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "myapp_connected_devices", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Upgrades Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(myapp_device_upgrade_total[1m])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Latency (Request Duration Histogram)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(myapp_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(myapp_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(myapp_request_duration_seconds_bucket[1m])) by (le))",
     "legendFormat": "P50"
    }
   ]
  },
  {
   "title": "Latency (Request Duration Summary)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "myapp_login_request_duration_seconds{quantile=\"0.99\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "myapp_login_request_duration_seconds{quantile=\"0.9\"}",
     "legendFormat": "P90"
    },
    {
     "expr": "myapp_login_request_duration_seconds{quantile=\"0.5\"}",
     "legendFormat": "P50"
    }
   ]
  }
 ]
}
{
 "title": "MyJob",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Panel Title",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "basic_count_total", "legendFormat": "{{application}}" }
   ]
  },
  {
   "title": "Random Number",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "random_per_second", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Iteration Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "basic_count_total", "legendFormat": "{{__name__}}" }
   ]
  }
 ]
}