apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  # Using annotations from kustomization.yaml file!
spec:
  selector:
    app: grafana
  type: LoadBalancer
  sessionAffinity: None
  ports:
    - port: 3000
      protocol: TCP
      targetPort: http-grafana