apiVersion: v1
kind: Service
metadata:
  name: pushgateway
  namespace: monitoring
  # Using annotations from kustomization.yaml file!
spec:
  selector:
    app: pushgateway
  type: LoadBalancer
  ports:
    - port: 9091
      targetPort: 9091
      nodePort: 31500
