apiVersion: v1
kind: Service
metadata:
  name: myapp-devices-svc
spec:
  selector:
    app: myapp
  type: NodePort
  ports:
  - name: devices
    protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-metrics-svc
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: 8081