apiVersion: v1
kind: Service
metadata:
  name: myapp-devices-svc
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: MC_ansible-rg_moving-lemur-k8s_eastus2
    service.beta.kubernetes.io/azure-pip-name: 341c32a8-888d-4ba9-94f4-401589e5dd1c
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - name: devices
    protocol: TCP
    port: 8080
    targetPort: 8080
    # nodePort: 31000
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-metrics-svc
spec:
  selector:
    app: myapp
  type: ClusterIP
  ports:
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: 8081