apiVersion: v1
kind: Service
metadata:
  name: myapp-svc
  # Using annotations from kustomization.yaml file!
spec:
  selector:
    app: myapp
  type: LoadBalancer
  ports:
  - name: devices
    protocol: TCP
    port: 8080
    targetPort: 8080
  - name: metrics
    protocol: TCP
    port: 8081
    targetPort: 8081